[package]
name = "muse2"
version = "0.1.0"
authors = ["Hawkes Research Group @ Chemical Engineering, Imperial College London <a.hawkes@imperial.ac.uk>", "Imperial College London RSE Team <ict-rse-team@imperial.ac.uk>"]
edition = "2021"
description = "A tool for running simulations of energy systems"
documentation = "https://energysystemsmodellinglab.github.io/MUSE_2.0"
readme = "README.md"
repository = "https://github.com/EnergySystemsModellingLab/MUSE_2.0"
license = "GPL-3.0-only"
keywords = ["energy", "modelling"]
categories = ["science", "simulation", "command-line-utilities"]

[dependencies]
csv = "1.3.0"
serde = {version = "1.0.202", features = ["derive"]}
toml = "0.8.13"
