[package]
name = "muse2"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
highs = "1.6.1"
itertools = "0.12.1"
polars = {version = "0.39.2", features = ["lazy", "csv"]}
serde = {version = "1.0.202", features = ["derive"]}
