[package]
name = "muse2"
version = "2.0.0-dev1"
authors = ["Hawkes Research Group @ Chemical Engineering, Imperial College London <a.hawkes@imperial.ac.uk>", "Imperial College London RSE Team <ict-rse-team@imperial.ac.uk>"]
edition = "2021"
description = "A tool for running simulations of energy systems"
documentation = "https://energysystemsmodellinglab.github.io/MUSE_2.0"
readme = "README.md"
repository = "https://github.com/EnergySystemsModellingLab/MUSE_2.0"
license = "GPL-3.0-only"
keywords = ["energy", "modelling"]
categories = ["science", "simulation", "command-line-utilities"]

[dependencies]
anyhow = "1.0.93"
csv = "1.3.0"
log = "0.4.22"
float-cmp = "0.10.0"
itertools = "0.13.0"
log-panics = "2.1.0"
serde = {version = "1.0.202", features = ["derive", "rc"]}
serde_string_enum = "0.2.1"
tempfile = "3.10.1"
toml = "0.8.13"
unicase = "2.7.0"
fern = {version = "0.7.0", features = ["chrono", "colored"]}
atty = "0.2"
chrono = "0.4"
clap = {version = "4.5.21", features = ["cargo", "derive"]}
