# Clippy configuration file
# This file contains configuration for clippy lints that cannot be easily configured in Cargo.toml

# Things that should not be treated as identifiers. The ".." represents the default options.
doc-valid-idents = ["HiGHS", ".."]
