name: muse2-input
resources:
  - name: agent_commodity_portions
    path: agent_commodity_portions.csv
    schema: agent_commodity_portions.yaml
  - name: agent_cost_limits
    path: agent_cost_limits.csv
    schema: agent_cost_limits.yaml
  - name: agent_objectives
    path: agent_objectives.csv
    schema: agent_objectives.yaml
  - name: agent_search_space
    path: agent_search_space.csv
    schema: agent_search_space.yaml
  - name: agents
    path: agents.csv
    schema: agents.yaml
  - name: assets
    path: assets.csv
    schema: assets.yaml
  - name: commodities
    path: commodities.csv
    schema: commodities.yaml
  - name: commodity_levies
    path: commodity_levies.csv
    schema: commodity_levies.yaml
  - name: demand
    path: demand.csv
    schema: demand.yaml
  - name: demand_slicing
    path: demand_slicing.csv
    schema: demand_slicing.yaml
  - name: process_availabilities
    path: process_availabilities.csv
    schema: process_availabilities.yaml
  - name: process_flows
    path: process_flows.csv
    schema: process_flows.yaml
  - name: process_parameters
    path: process_parameters.csv
    schema: process_parameters.yaml
  - name: processes
    path: processes.csv
    schema: processes.yaml
  - name: regions
    path: regions.csv
    schema: regions.yaml
  - name: time_slices
    path: time_slices.csv
    schema: time_slices.yaml
