resources:
  - description: |
      Time slices define how the year is divided up. Each time slice is composed of a season and a
      time of day. Often, this is written separated by a dot (e.g. `winter.day`).
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: time_slices
    notes:
      - The fractions for the different time slices must sum to one.
    path: time_slices.csv
    schema:
      fields:
        - description: Name of season
          name: season
          type: string
        - description: Name of time of day
          name: time_of_day
          type: string
        - description: Fraction of year
          name: fraction
          notes: Must be >0 and <=1
          type: number
    scheme: file
    type: table
  - description: Describes regions in the system.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: regions
    path: regions.csv
    schema:
      fields:
        - description: A unique identifier for a region
          name: id
          type: string
        - description: A human-readable label for the region
          name: description
          type: string
    scheme: file
    type: table
  - description: Portions of commodity demand for which agents are responsible.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: agent_commodity_portions
    notes:
      - If an entry is specified for one agent and commodity, there must be entries covering
        all milestone years.
      - For each agent listed in this file, the total portions for each region/commodity/year
        combination must sum to one.
      - In addition, there must be entries for every SVD and SED commodity for all regions
        and milestone years.
    path: agent_commodity_portions.csv
    schema:
      fields:
        - description: The agent to apply these values to
          name: agent_id
          type: string
        - description: The commodity for which the agent is responsible
          name: commodity_id
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: Portion of commodity demand
          name: commodity_portion
          notes: Value must be >0 and <=1. The portion applies only to the specified years.
          type: number
    scheme: file
    type: table
  - description: Limits on expenditure for agents.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: agent_cost_limits
    notes:
      - If cost limits are provided for an agent, they must be present for all years.
    path: agent_cost_limits.csv
    schema:
      fields:
        - description: The agent to apply these values to
          name: agent_id
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: Maximum capital cost the agent will pay
          name: capex_limit
          notes: Must be >0. Optional (defaults to infinity).
          type: number
        - description: Maximum annual operating cost
          name: annual_cost_limit
          notes: |
            The maximum annual operating cost (fuel plus variable operating cost
            etc.) that the agent will pay. Must be >0. Optional (defaults to infinity).
          type: number
    scheme: file
    type: table
  - description: Describes the agents' objectives.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: agent_objectives
    notes:
      - Every agent must have one objective for each milestone year.
      - If the weighted sum decision rule is in use, the `decision_weight` value must
        be provided, otherwise it must be omitted.
      - If the lexico decision rule is in use, the `decision_lexico_order` value must
        be provided, otherwise it must be omitted.
    path: agent_objectives.csv
    schema:
      fields:
        - description: An agent ID
          name: agent_id
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: The type of objective
          enum:
            - lcox
            - npv
          name: objective_type
          notes: |
            Must be `npv` (net present value) or `lcox` (levelised cost of X). Note that support for
            LCOX is experimental and may give bad results.
          type: string
        - description: Weight for weighted sum decision rule
          name: decision_weight
          notes: Currently unused
          type: number
        - description: Order in which to consider objectives for lexico decision rule
          name: decision_lexico_order
          notes: Currently unused
          type: integer
    scheme: file
    type: table
  - description: Defines the processes in which an agent will invest for given parameters.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: agent_search_space
    notes:
      - If entries are missing for any combination of agent, commodity or milestone year,
        then it is assumed that all processes can be considered in this case.
    path: agent_search_space.csv
    schema:
      fields:
        - description: An agent ID
          name: agent_id
          type: string
        - description: The commodity to which this entry applies
          name: commodity_id
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: The processes in which this agent will invest
          name: search_space
          notes: |
            One or more process IDs separated by semicolons. If this field is empty
            or `all`, all processes will be considered.
          type: string
    scheme: file
    type: table
  - description: Describes agents in the system
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: agents
    path: agents.csv
    schema:
      fields:
        - description: A unique identifier for an agent
          name: id
          type: string
        - description: A human-readable label for the agent
          name: description
          type: string
        - description: The region(s) in which the agent operates
          name: regions
          notes: One or more region IDs, separated by semicolons or the string `all`
          type: string
        - description: The decision rule applied to objectives
          name: decision_rule
          notes: Currently the only supported rule is `simple`
          type: string
        - description: Tolerance for `lexico` decision rule
          name: decision_lexico_tolerance
          notes: Currently unused
          type: number
    scheme: file
    type: table
  - description: Defines assets in the system
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: assets
    path: assets.csv
    schema:
      fields:
        - description: The process of which this asset is an instance
          name: process_id
          type: string
        - description: The region in which this agent operates
          name: region_id
          type: string
        - description: The agent to which this asset belongs
          name: agent_id
          type: string
        - description: The capacity of the asset
          name: capacity
          notes: Must be >0
          type: number
        - description: The year in which to commission this asset
          name: commission_year
          notes: |
            This value can be any integer >=0. If it is before the start of the simulation, it will
            already be commissioned in the first year and if it after the end of the simulation then
            it will never be commissioned.
          type: integer
    scheme: file
    type: table
  - description: Describes commodities in the system.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: commodities
    notes:
      - Every SED (supply equals demand) commodity must have both producer and consumer
        processes for every region and milestone year.
      - Every SVD (service demand) commodity must have a producer for every region and
        milestone year.
    path: commodities.csv
    schema:
      fields:
        - description: A unique identifier for the commodity
          name: id
          type: string
        - description: A human-readable label for the commodity
          name: description
          type: string
        - description: The type of commodity
          name: type
          notes: |
            Must be one of `svd` (service demand), `sed` (supply equals demand), `inc` (input
            commodity) or `ouc` (output commodity)
          type: string
        - description: |
            The time slice level at which constraints for this commodity are applied
          name: time_slice_level
          notes: |
            Must be one of `annual` (whole year), `season` (whole season) or `daynight` (a
            particular time of day)
          type: string
    scheme: file
    type: table
  - description: Defines levies for commodities (or, if `value` is negative, incentives).
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: commodity_levies
    notes:
      - If an entry is included for a given combination of commodity and region, entries
        must be provided covering all milestone years and time slices.
    path: commodity_levies.csv
    schema:
      fields:
        - description: The commodity to which this entry applies
          name: commodity_id
          type: string
        - description: The region(s) to which this entry applies
          name: regions
          notes: One or more region IDs, separated by semicolons or the string `all`
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: The time slices(s) to which this entry applies
          name: time_slice
          notes: |
            Can be a single time slice (e.g. `winter.day`), a whole season (e.g. `winter`) or
            `annual`, representing the whole year
          type: string
        - description: The type of balance to which this is applied
          name: balance_type
          notes: |
            Can be `cons` (applies to consumption only), `prod` (applies to production only) or
            `net` (applies to consumption and production)
          type: string
        - description: The value of the levy/incentive
          name: value
          type: number
    scheme: file
    type: table
  - description: Specifies the demand for service demand commodities.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: demand
    notes:
      - Every service demand commodity must have entries in this file covering every combination
        of milestone year and region
    path: demand.csv
    schema:
      fields:
        - description: The service demand commodity to which this entry applies
          name: commodity_id
          type: string
        - description: The region to which this entry applies
          name: region_id
          notes: A region ID
          type: string
        - description: The year(s) to which this entry applies
          name: year
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: Total demand for this year
          name: demand
          type: number
    scheme: file
    type: table
  - description: Specifies how demand is distributed throughout the year (i.e. for different
      milestones).
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: demand_slicing
    notes:
      - The user must provide entries covering every combination of service demand commodity,
        region and time slice.
      - For each combination, the sum of the fractions must equal one.
    path: demand_slicing.csv
    schema:
      fields:
        - description: The service demand commodity to which this entry applies
          name: commodity_id
          type: string
        - description: The region to which this entry applies
          name: region_id
          notes: A region ID
          type: string
        - description: The time slices(s) to which this entry applies
          name: time_slice
          notes: |
            Can be a single time slice (e.g. `winter.day`), a whole season (e.g. `winter`) or
            `annual`, representing the whole year
          type: string
        - description: The fraction of annual demand for this entry
          name: fraction
          notes: Must be >0 and <=1
          type: number
    scheme: file
    type: table
  - description: Defines how much of a process's capacity is available throughout the
      year.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: process_availabilities
    notes:
      - Must be provided for every process.
      - Only one type of limit can be supplied for each combination of process/region/year/time
        slice.
    path: process_availabilities.csv
    schema:
      fields:
        - description: The process to which this entry applies
          name: process_id
          type: string
        - description: The region(s) to which this entry applies
          name: regions
          notes: One or more region IDs, separated by semicolons or the string `all`
          type: string
        - description: The milestone year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: The time slices(s) to which this entry applies
          name: time_slice
          notes: |
            Can be a single time slice (e.g. `winter.day`), a whole season (e.g. `winter`) or
            `annual`, representing the whole year
          type: string
        - description: The type of limit
          name: limit_type
          notes: |
            Can be `lo` (a lower bound), `hi` (an upper bound) or `fx` (indicating that the
            availability is constant)
          type: string
        - description: The proportion of capacity which is available
          name: value
          notes: Must be >0 and <=1
          type: number
    scheme: file
    type: table
  - description: The commodity flows for each process
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: process_flows
    notes:
      - Commodity flows can vary by region and year.
      - For each process, there must be entries covering all the years and regions in
        which the process operates.
    path: process_flows.csv
    schema:
      fields:
        - description: The process to which this entry applies
          name: process_id
          type: string
        - description: The commodity for this flow
          name: commodity_id
          type: string
        - description: The region(s) to which this entry applies
          name: regions
          notes: |
            One or more region IDs, separated by semicolons or the string `all`. Must be regions in
            which the process operates.
          type: string
        - description: The year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: The flow for this commodity
          name: coeff
          notes: |
            Can be <0, indicating an input flow, or >0, indicating an output flow. Cannot be zero.
          type: number
        - description: The type of commodity flow
          name: type
          notes: Currently this value must be `fixed`
          type: string
        - description: The cost per unit flow
          name: cost
          notes: Optional. If present, must be >0.
          type: number
    scheme: file
    type: table
  - description: Parameters for processes which vary by region and year.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: process_parameters
    notes:
      - For each process, entries must be provided which cover every combination of milestone
        year and region in which the process operates.
    path: process_parameters.csv
    schema:
      fields:
        - description: The process to which this entry applies
          name: process_id
          type: string
        - description: The region(s) to which this entry applies
          name: regions
          notes: |
            One or more region IDs, separated by semicolons or the string `all`. Must be regions in
            which the process operates.
          type: string
        - description: The milestone year(s) to which this entry applies
          name: years
          notes: One or more milestone years separated by semicolons or `all`
          type: string
        - description: Overnight capital cost per unit capacity
          name: capital_cost
          type: number
        - description: Annual operating cost per unit capacity
          name: fixed_operating_cost
          type: number
        - description: Annual variable operating cost per unit activity
          name: variable_operating_cost
          type: number
        - description: Lifetime in years of an asset created from this process
          name: lifetime
          notes: Must be a positive integer
          type: integer
        - description: Process-specific discount rate
          name: discount_rate
          notes: Must be positive. A warning will be issued if this number is >1.
          type: number
        - description: |
            Factor for calculating the maximum consumption/production over a year.
          name: capacity_to_activity
          notes: Must be >=0
          type: number
    scheme: file
    type: table
  - description: Describes processes in the system.
    encoding: utf-8
    format: csv
    mediatype: text/csv
    name: processes
    path: processes.csv
    schema:
      fields:
        - description: A unique identifier for a process
          name: id
          type: string
        - description: A human-readable label for the process
          name: description
          type: string
        - description: The region(s) in which this process can operate
          name: regions
          notes: One or more region IDs, separated by semicolons or the string `all`
          type: string
        - description: The primary output commodity, if any, for this process
          name: primary_output
          notes: |
            This field *must* be omitted for processes with only input flows. It *can* be omitted if
            there is only one output flow, in which can it will be inferred.
          type: string
        - description: The first year when this process is available to agents
          name: start_year
          type: integer
        - description: The last year when this process is available to agents
          name: end_year
          notes: Must be >= to `start_year`
          type: integer
    scheme: file
    type: table
