[agents]
agents_file_path = "agents.csv"

[agent_objectives]
agent_objectives_file_path = "agent_objectives.csv"

[agent_regions]
agent_regions_file_path = "agent_regions.csv"

[assets]
assets_file_path = "assets.csv"

[commodities]
commodities_file_path = "commodities.csv"

[commodity_constraints]
commodity_constraints_file_path = "commodity_constraints.csv"

[commodity_costs]
commodity_costs_file_path = "commodity_costs.csv"

[demand]
demand_file_path = "demand.csv"

[demand_slicing]
demand_slicing_file_path = "demand_slicing.csv"

[processes]
processes_file_path = "processes.csv"

[process_availabilities]
process_availabilities_file_path = "process_availabilities.csv"

[processes_flow_share_constraints]
process_flow_share_constraints_file_path = "processes_flow_share_constraints.csv"

[process_flows]
process_flows_file_path = "process_flows.csv"

[process_investment_constraints]
process_investment_constraints_file_path = "process_investment_constraints.csv"

[process_pacs]
process_pacs_file_path = "process_pacs.csv"

[process_parameters]
process_parameters_file_path = "process_parameters.csv"

[process_regions]
process_regions_file_path = "process_regions.csv"

[regions]
regions_file_path = "regions.csv"

[time_slices]
time_slices_path = "time_slices.csv"

[milestone_years]
years = [2020]
