[input_files]
regions_file_path = "regions.csv"
commodities_file_path = "commodities.csv"
commodity_net_costs_file_path = "commodity_net_costs.csv"
commodity_constraints_file_path = "commodity_constraints.csv"
demand_file_path = "demand.csv"
demand_slicing_file_path = "demand_slicing.csv"
processes_file_path = "processes.csv"
processes_flows_file_path = "process_availabilities.csv"
processes_availabilities_file_path = "process_flows.csv"
processes_flow_constraints_file_path = "processes_flow_share_constraints.csv"
assets_file_path = "assets.csv"
time_slices_path = "time_slices.csv"

[milestone_years]
years = [2020]
