[global]
log_level = "info"

[input_files]
agents_file_path = "agents.csv"
agent_objectives_file_path = "agent_objectives.csv"
agent_regions_file_path = "agent_regions.csv"
assets_file_path = "assets.csv"
commodities_file_path = "commodities.csv"
commodity_constraints_file_path = "commodity_constraints.csv"
commodity_costs_file_path = "commodity_costs.csv"
demand_file_path = "demand.csv"
demand_slicing_file_path = "demand_slicing.csv"
processes_file_path = "processes.csv"
process_availabilities_file_path = "process_availabilities.csv"
process_flow_share_constraints_file_path = "process_flow_share_constraints.csv"
process_flows_file_path = "process_flows.csv"
process_investment_constraints_file_path = "process_investment_constraints.csv"
process_pacs_file_path = "process_pacs.csv"
process_parameters_file_path = "process_parameters.csv"
process_regions_file_path = "process_regions.csv"
regions_file_path = "regions.csv"
time_slices_file_path = "time_slices.csv"

[milestone_years]
years = [2020, 2100]
