# Heavily borrows from
# https://github.com/dora-rs/dora/blob/main/.github/workflows/cargo-update.yml

name: Update Cargo.lock

on:
  schedule:
    # Dependabot visits on Weds, so run on Thurs
    - cron: "0 0 * * 4"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  cargo-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Update dependencies
        run: cargo update

      - name: Set user name and email for git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a branch for the update
        run: |
          git switch --force-create update-cargo-lock
          git add Cargo.lock
          git commit -m "chore: Update Cargo.lock" || echo success=false > $GITHUB_OUTPUT
          git push origin update-cargo-lock --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Open a pull request using GitHub CLI
        if: steps.checker.outputs.success != 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "chore: Update Cargo.lock" \
            --body "Automated weekly update of Cargo.lock via \`cargo update\`." \
            --base ${{ github.ref_name }} \
            --head update-cargolock \
            --label "dependencies" \
            || gh pr edit --base main
