name: Check for cargo doc warnings

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Check docs
    runs-on: ubuntu-latest
    env:
      # Make warnings fatal
      RUSTDOCFLAGS: -D warnings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cargo Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ubuntu-latest-cargo-${{ hashFiles('Cargo.toml') }}
          restore-keys: |
            ubuntu-latest-cargo-${{ hashFiles('Cargo.toml') }}
            ubuntu-latest-cargo

      - name: Check docs
        run: cargo doc --no-deps
