name: Check documentation + hyperlinks
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # midnight every Monday

jobs:
  check-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set user name and email for git
        run: |
          # Needed so we can apply patches
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - uses: ./.github/actions/generate-docs
        with:
          build: all_with_old

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--verbose --no-progress --accept 200,203,503 --exclude-path ^target/ --exclude-path ^docs/ --exclude-path ^book/404.html$ './**/*.md' './**/*.html'"
