name: Check links in Markdown files
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # midnight every Monday

jobs:
  check-links:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
