name: Check documentation + hyperlinks
on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * 1" # midnight every Monday

jobs:
  check-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/generate-docs

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
