name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: MUSE 2.0
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: |
          # self update is currently broken on Windows runners:
          #   https://github.com/rust-lang/rustup/issues/3709
          rustup update --no-self-update ${{ matrix.toolchain }}
          rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
