name: Run pre-commit hooks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: [ubuntu-latest]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: pre-commit/action@v3.0.1
      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
